name: 'eonx-com/actions-opsgenie'
description: 'Send an alert using OpsGenie API V2'
author: 'Damian Sloane <damian.sloane@eonx.com>'

branding:
  icon: 'x'
  color: 'red'

inputs:
  alias:
    description: 'Unique identifier for this type of alert (used to de-duplicate alerts)'
    required: true
  priority:
    description: 'Alert priority level (one of the P1-P5 OpsGenie alert levels)'
    required: true
  message:
    description: 'Message to attach to the alert'
    required: true
  api_key:
    description: 'OpsGenie API Key'
    required: true
  respondes:
    description: 'Optional comma separated list of responders to be added. Responders have the format id:{UUID}:{type} OR name:{TeamName}:{type} OR username:Email:{type}. {type} is one of team, user, escalation, schedule - refer to Opsgenie docs'
    required: false
    default: ""
  tags:
    description: 'Optional comma separated list of tags to add the the alert'
    required: false
    default: ""
  use_eu_instance:
    description: 'Use EU instance'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.message }}
    - ${{ inputs.priority }}
    - ${{ inputs.api_key }}
    - ${{ inputs.use_eu_instance }}
    - ${{ inputs.responders }}
    - ${{ inputs.tags }}
